import Head from 'next/head'
import Hero from '../components/Hero'
import Nav from '../components/Nav'

export default function Home() {
  return (
    <div className="-z-50">
            <Head>
                <title>Vendetti Studios</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Nav />
            <Hero />
    </div>
  )
}
