import Head from 'next/head'

export default function Home() {
  return (
    <div className="-z-50">
            <Head>
                <title>Vendetti Studios</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
    </div>
  )
}
